# Docker Compose configuration for ThetaData Terminal
services:
  theta-terminal:
    build: .
    image: thetadata/terminal:latest
    container_name: theta-terminal
    restart: unless-stopped

    # Port mapping - host:container
    ports:
      - "25510:25510"  # HTTP REST API
      - "25520:25520"  # WebSocket
      - "11000:11000"  # Python API (MDDS)
      - "10000:10000"  # Python API (FPSS)

    # Performance optimizations (USE WITH CAUTION)
    # privileged: true
    # network_mode: host
    # security_opt:
    #   - seccomp:unconfined

    # Remove port mappings (not needed with host networking)
    # ports:
    #   - "25510:25510"
    #   - "25520:25520"
    #   - "11000:11000"
    #   - "10000:10000"

    # Environment variables
    environment:
      # Option 1: Set credentials via environment variables
      THETA_USERNAME: "${THETA_USERNAME}"
      THETA_PASSWORD: "${THETA_PASSWORD}"

      # Java memory settings
      JAVA_OPTS: "-Xms2G -Xmx6G"

      # Timezone (optional)
      TZ: "America/New_York"

    # Volumes for persistence
    volumes:
      # Config directory
      - ./config:/opt/theta/config
      # Logs directory
      - ./logs:/opt/theta/logs
      # Trust/certificate files - mount all possible locations
      - ./theta-data:/root/ThetaData/ThetaTerminal
      - ./theta-data:/root/.theta

    # Command (customize as needed)
    command: ["--config=/opt/theta/config/config_0.properties"]
